group = dev.aoqia.leaf
name = yarn
description = Zomboid mappings used by leaf (FabricMC/fabric fork).
zomboidVersion = 41.78.16
url = https://github.com/aoqia194/leaf-yarn

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Loom properties needed for applying it
leaf.loom.onlyProvideJars=true
leaf.loom.dontRemap=true

# Dependencies
enigma_version=2.5.1
unpick_version=2.3.0
cfr_version=0.2.2
vineflower_version=1.11.1
asm_version=9.6

# Javadoc generation/linking
leaf_loader_version=0.1.0
jetbrains_annotations_version=24.1.0

# Build logic
tiny_remapper_version=0.10.4
junit_version=5.11.0
assertj_version=3.26.3
