name: Release

on: workflow_dispatch

# Release job concurrency for multiple branch release at once.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    # Needed for Jreleaser to update CHANGELOG.md
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build/

      - name: Generate Build Number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: "build/${{ github.ref }}"

      - name: Deploy
        # TODO: Uncomment after initial release to generate metadata xml
#        run: ./gradlew checkVersion publish -S
        run: ./gradlew publish -S

# Don't publish to Gradle Portal, it creates more hassle then fixes.
#      - name: Release Plugin (Gradle Plugin Portal)
#        env:
#          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
#          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
#        run: ./gradlew publishPlugins -S

      - name: Release Plugin (Sonatype Maven Central)
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE_KEY: ${{ secrets.GPG_PASSPHRASE_KEY }}
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
        run: ./gradlew jreleaserFullRelease -S
